**1)Cargo mi DATA**

In [34]:
import pandas as pd
df=pd.read_excel('https://github.com/CamilaBracamonte/PC2.1/blob/main/HDI%20(4).xlsx?raw=true',header=4)
df

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
4,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

2)

In [31]:
cols_to_keep = df.columns[:2] #Eliminacion de columnas que tienen nombres NaN en su primera fila, excepto las 2 primeras

df_nuevo = pd.concat([df[cols_to_keep], df.loc[:, df.iloc[0].notna()].iloc[:, 2:]], axis=1)
df_nuevo

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $)
1,NaN,NaN,2021,2021,2021,2021,2021
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454
4,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622
...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

SyntaxError: invalid syntax (<ipython-input-26-ba5870b1a0ea>, line 1)