## PRACTICA CALIFICADA 2
Camila Bracamonte - 20223376

**1. Cargo mi DATA**

In [1]:
import pandas as pd
df=pd.read_excel('https://github.com/CamilaBracamonte/PC2.1/blob/main/HDI%20(4).xlsx?raw=true',header=4)
df

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3
4,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**2. Me quedo con las columnas que no contienen N/A**

In [2]:
df2=df.iloc[:,[0,1,2,4,6,8,10,12,14]]
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...,...
267,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**3. Me quedo con las filas necesarias y agrego una nueva columna**

In [3]:
df2=df2.iloc[0:197]
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187
193,188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1,188
194,189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3,189
195,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190
196,191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1,191

In [4]:
df2=df2.drop(index=[0,1,2,69,119,164])
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
3,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
4,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
5,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
6,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
7,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187
193,188,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1,188
194,189,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3,189
195,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190
196,191,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1,191

**4. Cambio mis datos de object a float para poder trabajar con ellos (algebraicamente)**

In [5]:
for col in df2.columns[2:7]:
    df2[col] = pd.to_numeric(df2[col], errors='coerce')
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
3,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,5,3
4,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,6,1
5,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,11,2
6,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,6,4
7,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,18,5
...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187
193,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1,188
194,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3,189
195,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190
196,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1,191

**5) Verifico que mis columnas deseadas estén en el formato de float**

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 3 to 196
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Unnamed: 0                              191 non-null    object
 1   Unnamed: 1                              191 non-null    object
 2   Human Development Index (HDI)           191 non-null    float64
 3   Life expectancy at birth                191 non-null    float64
 4   Expected years of schooling             191 non-null    float64
 5   Mean years of schooling                 191 non-null    float64
 6   Gross national income (GNI) per capita  191 non-null    float64
 7   GNI per capita rank minus HDI rank      191 non-null    object
 8   HDI rank                                191 non-null    object
dtypes: float64(5), object(4)
memory usage: 19.0+ KB

**6) Como quité cierta información de la columna de países, agrego una nueva columna con la información eliminada**

In [7]:
df2['Rango Human Development'] = pd.cut(df2["Human Development Index (HDI) "], bins=[0,0.549, 0.699, 0.796,1], labels=['LOW', 'MEDIUM', 'HIGH', 'VERY HIGH'])
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank,Rango Human Development
3,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,5,3,VERY HIGH
4,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,6,1,VERY HIGH
5,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,11,2,VERY HIGH
6,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,6,4,VERY HIGH
7,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,18,5,VERY HIGH
...,...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187,LOW
193,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1,188,LOW
194,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3,189,LOW
195,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190,LOW
196,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1,191,LOW

**7) Renombro mis dos encabezados sin títulos**

In [8]:
df2.rename({"Unnamed: 0": "HDI Rank", "Unnamed: 1": "Country","HDI rank":"HDI 2020 Rank"}, axis='columns')

,HDI Rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI 2020 Rank,Rango Human Development
3,1,Switzerland,0.962,83.9872,16.500299,13.859660,66933.004540,5,3,VERY HIGH
4,2,Norway,0.961,83.2339,18.185200,13.003630,64660.106220,6,1,VERY HIGH
5,3,Iceland,0.959,82.6782,19.163059,13.767170,55782.049810,11,2,VERY HIGH
6,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62606.845400,6,4,VERY HIGH
7,5,Australia,0.951,84.5265,21.054590,12.726820,49238.433350,18,5,VERY HIGH
...,...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4,187,LOW
193,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1,188,LOW
194,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3,189,LOW
195,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7,190,LOW
196,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1,191,LOW

**8) Arreglo una columna de datos que había reconocido la coma como punto, por lo que para cambiarlo de forma sencilla, aprovecho que cambié mis datos a float y puedo trabajar algebraicamente con esta columna**

In [9]:
df2["Gross national income (GNI) per capita"]=df2["Gross national income (GNI) per capita"]/1000
df2

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank,Rango Human Development
3,1,Switzerland,0.962,83.9872,16.500299,13.859660,66.933005,5,3,VERY HIGH
4,2,Norway,0.961,83.2339,18.185200,13.003630,64.660106,6,1,VERY HIGH
5,3,Iceland,0.959,82.6782,19.163059,13.767170,55.782050,11,2,VERY HIGH
6,4,"Hong Kong, China (SAR)",0.952,85.4734,17.278170,12.226210,62.606845,6,4,VERY HIGH
7,5,Australia,0.951,84.5265,21.054590,12.726820,49.238433,18,5,VERY HIGH
...,...,...,...,...,...,...,...,...,...,...
192,187,Burundi,0.426,61.6627,10.722722,3.129267,0.731787,4,187,LOW
193,188,Central African Republic,0.404,53.8947,8.040172,4.334000,0.966059,1,188,LOW
194,189,Niger,0.400,61.5763,6.957112,2.116717,1.239867,-3,189,LOW
195,190,Chad,0.394,52.5254,8.035914,2.573774,1.364169,-7,190,LOW
196,191,South Sudan,0.385,54.9752,5.542510,5.726140,0.767787,-1,191,LOW

9) Verifico que no haya cambiado mi formato de datos

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 3 to 196
Data columns (total 10 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Unnamed: 0                              191 non-null    object
 1   Unnamed: 1                              191 non-null    object
 2   Human Development Index (HDI)           191 non-null    float64
 3   Life expectancy at birth                191 non-null    float64
 4   Expected years of schooling             191 non-null    float64
 5   Mean years of schooling                 191 non-null    float64
 6   Gross national income (GNI) per capita  191 non-null    float64
 7   GNI per capita rank minus HDI rank      191 non-null    object
 8   HDI rank                                191 non-null    object
 9   Rango Human Development                 191 non-null    category
dtypes: category(1), float64(5), object(4)
memory usage: 19.4+ KB

# Al final, me queda mi dataframe con la siguiente infromación:

1.   HD1 Rank
2. Country
3.   Human Development Index (HDI)
4. Life expentancy at birth
5. Expected years of schooling
6. Mean years of schooling
7. Gross national income (GNI) per capita
8. GNI per capita rank minus HDI rank
9. HDI 2020 Rank
10. Rango Human Development